import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.variable} antialiased`}>
        <div className="bg-stone-400 min-w-screen min-h-screen">
          <div className="container mx-auto py-4">
            <div className="w-full py-2 bg-red-200 rounded border-2">
              <div className="flex gap-x-2 justify-center">
                <p className="p-1 text-center">
                  <span className="font-bold">Elf Faction:</span> Ruddy Reds
                </p>
                <p className="p-1">|</p>
                <p className="p-1 text-center">
                  <span className="font-bold">Action points left:</span> 3
                </p>
                <p className="p-1">|</p>
                <p className="p-1 text-center">
                  <span className="font-bold">Teams current score:</span> 3
                </p>
              </div>
            </div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
